import Head from 'next/head'
import { TextLoader } from "langchain/document_loaders/fs/text";

export default function Test(docs) {

  return (
    <div className="container">
      <Head>
        <title>Let's play</title>
        <meta name="description" content="Generated by kontopro" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          Let's play with Langchain and Next.js!
        </h1>

        <p>First things first: Supabase with pg vector enabled!!</p>
        {docs}

      </main>

      <footer className="footer">
        <p>Powered by{' '} kontopro</p>
          
      </footer>
    </div>
  )
}

export async function getStaticProps( ){
  
const loader = new TextLoader("small.txt");
const docs = await loader.load();

return {
  props: {docs}
}
}
