import Head from 'next/head'
import { PDFLoader } from "langchain/document_loaders/fs/pdf";

export default function Test({docs}) {

  return (
    <div className="container">
      <Head>
        <title>Let's play</title>
        <meta name="description" content="Generated by kontopro" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          Let's play with Langchain and Next.js!
        </h1>
        <p>First things first: Supabase with pg vector enabled!!</p>
       <p>{docs}</p> 
      </main>

      <footer className="footer">
        <p>Powered by{' '} kontopro</p>
          
      </footer>
    </div>
  )
}

export async function getStaticProps( ){
  
    const loader = new PDFLoader("dummy2.pdf"
    , {splitPages: false}
    );
    const documents= await loader.load();
    const docs= documents[0].pageContent;
    console.log(docs)

    return {
    props: {docs}
    }
}
