import Head from 'next/head'
import { PDFLoader } from "langchain/document_loaders/fs/pdf";

export default function TestPDF({docs}) {

  return (
    <div className="container">
      <Head>
        <title>Let&apos; s play</title>
        <meta name="description" content="Generated by kontopro" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">We read the pdf with Langchain PDFLoader!</h1>
        <p>However the public folder of nextjs cannot be read by this loader, so we stored it in our root project folder. Next paragraph is the pageContent of the loaded pdf</p>
        <p>So the solution:        </p>
        <p>1. User inputs the file (we should also see the drag n drop)        </p>
        <p>2. User sees some info of the selected file and confirms uploading (also check sizes)       </p>
        <p>3. On confirmation we upload/store the file to supabase storage </p>
        <p>4. On upload/store completion we return the public url to langchain PDFLoader and we store the contents to database (<i>document</i> and <i>document_content</i> table ) returning the document id</p>
        <p>5. We create embeddings? or can we chat before creating embeddings??</p>
        <p>6. Start chatting</p>
       <p>{docs}</p> 
      </main>

      <footer className="footer">
        <p>Powered by{' '} kontopro</p>
          
      </footer>
    </div>
  )
}

export async function getStaticProps( ){
  
    const loader = new PDFLoader("dummy2.pdf"
    , {splitPages: false}
    );
    const documents= await loader.load();
    const docs= documents[0].pageContent;
    console.log(docs)

    return {
    props: {docs}
    }
}
