import Head from 'next/head'
import { PDFLoader } from "langchain/document_loaders/fs/pdf";
import { useState } from 'react';

export default function TestPDF({docs}) {

  return (
    <div className="container">
      <Head>
        <title>Let&apos; s play</title>
        <meta name="description" content="Generated by kontopro" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="main">
        <h1 className="title">
          New try!!
        </h1>
        <p>We try to upload with a drag&drop loader to see if i can make the PDFLoader of Langchain to read from public folder, which is the default asset serving folder of nextjs</p>
       <p>{docs}</p> 
       {/* <input type="file" id="input" onChange={handleFileSelection} /> */}
       {/* <p>the file name is {myfile.name}</p> */}
      </main>

      <footer className="footer">
        <p>Powered by{' '} kontopro</p>
          
      </footer>
    </div>
  )
}

export async function getStaticProps( ){
  
    const response = await fetch("https://xmnhlyhmbniuitsgwcgt.supabase.co/storage/v1/object/public/docai_bucket/jwts-not-safe-e-book.pdf");
    const pdfBlob = await response.blob();
    const loader = new PDFLoader(pdfBlob, {splitPages: false} );
    const documents= await loader.load();
    const docs= documents[0].pageContent;
    console.log(docs)

    return {
    props: {docs}
    }
}
